CREATE DATABASE IF NOT EXISTS he;

USE he;

CREATE TABLE IF NOT EXISTS turmas (
    turma VARCHAR(255) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS modulos (
    modulo VARCHAR(255) PRIMARY KEY NOT NULL,
    duracao INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS main (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    t VARCHAR(255) NOT NULL,
    m VARCHAR(255) NOT NULL,
    hrsDadas INT NOT NULL DEFAULT 0
);

ALTER TABLE main ADD FOREIGN KEY (t) REFERENCES turmas(turma);
ALTER TABLE main ADD FOREIGN KEY (m) REFERENCES modulos(modulo);

CREATE TABLE IF NOT EXISTS horario (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    turma VARCHAR(255) NOT NULL,
    versao INT NOT NULL,
    info JSON NOT NULL,
    img BLOB NOT NULL
)

ALTER TABLE horario ADD FOREIGN KEY (turma) REFERENCES turmas(turma);

CREATE TABLE IF NOT EXISTS apikeys (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    apiKEY VARCHAR(255) NOT NULL,
    apiSecret VARCHAR(255) NOT NULL,
    perms VARCHAR(255) NOT NULL, -- "read" or "write"
    PRIMARY KEY (id)
);



